export const HOME_UPLOAD_FILE_BEGIN = 'HOME_UPLOAD_FILE_BEGIN';
export const HOME_UPLOAD_FILE_SUCCESS = 'HOME_UPLOAD_FILE_SUCCESS';
export const HOME_UPLOAD_FILE_FAILURE = 'HOME_UPLOAD_FILE_FAILURE';
export const HOME_UPLOAD_FILE_DISMISS_ERROR = 'HOME_UPLOAD_FILE_DISMISS_ERROR';
export const HOME_SWITCH_HEADER = 'HOME_SWITCH_HEADER';
export const HOME_RESET_UPLOAD = 'HOME_RESET_UPLOAD';
