export const HOME_UPLOAD_FILE_BEGIN = 'HOME_UPLOAD_FILE_BEGIN';
export const HOME_UPLOAD_FILE_SUCCESS = 'HOME_UPLOAD_FILE_SUCCESS';
export const HOME_UPLOAD_FILE_FAILURE = 'HOME_UPLOAD_FILE_FAILURE';
export const HOME_UPLOAD_FILE_DISMISS_ERROR = 'HOME_UPLOAD_FILE_DISMISS_ERROR';
